# Generated by Django 5.2.12 on 2026-03-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "manufacturing_costs",
            "0004_manufacturingcost_active_manufacturingcost_inherited",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturingcost",
            name="amortization",
            field=models.DecimalField(
                decimal_places=6,
                default=1,
                help_text="How many units is this cost amortized over?",
                max_digits=19,
                verbose_name="Amortization",
            ),
        ),
    ]
