# Generated by Django 5.2.12 on 2026-03-29 09:42

import InvenTree.fields
import InvenTree.validators
from django.db import migrations, models


def set_default_amount(apps, schema_editor):
    """Initialize the 'amount' field for existing ManufacturingCost records."""
    ManufacturingCost = apps.get_model("manufacturing_costs", "ManufacturingCost")

    to_update = []

    for cost in ManufacturingCost.objects.all():
        cost.amount = str(cost.quantity)
        to_update.append(cost)

    if len(to_update) > 0:
        print(
            f"Initializing 'amount' field for {len(to_update)} ManufacturingCost records."
        )
        ManufacturingCost.objects.bulk_update(to_update, ["amount"])


class Migration(migrations.Migration):
    dependencies = [
        ("manufacturing_costs", "0005_manufacturingcost_amortization"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturingcost",
            name="amount",
            field=models.CharField(blank=True, max_length=25, verbose_name="Amount"),
        ),
        migrations.AlterField(
            model_name="manufacturingcost",
            name="amortization",
            field=InvenTree.fields.RoundingDecimalField(
                decimal_places=6,
                default=1,
                help_text="How many units is this cost amortized over?",
                max_digits=19,
                verbose_name="Amortization",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturingcost",
            name="quantity",
            field=InvenTree.fields.RoundingDecimalField(
                decimal_places=6,
                default=1,
                help_text="Quantity multiplier for this manufacturing cost",
                max_digits=19,
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturingrate",
            name="units",
            field=models.CharField(
                blank=True,
                help_text="Units for the manufacturing rate",
                max_length=50,
                validators=[InvenTree.validators.validate_physical_units],
                verbose_name="Units",
            ),
        ),
    ]
