# Generated by Django 5.2.12 on 2026-03-31 10:37

from django.db import migrations, models


def fix_empty_amounts(apps, schema_editor):
    """Fix any ManufacturingCost records with empty 'amount' field."""
    ManufacturingCost = apps.get_model("manufacturing_costs", "ManufacturingCost")

    to_update = []

    for cost in ManufacturingCost.objects.filter(amount=""):
        cost.amount = str(cost.quantity)
        to_update.append(cost)

    if len(to_update) > 0:
        print(
            f"Fixing empty 'amount' field for {len(to_update)} ManufacturingCost records."
        )
        ManufacturingCost.objects.bulk_update(to_update, ["amount"])

    assert ManufacturingCost.objects.filter(amount="").count() == 0, (
        "There are still ManufacturingCost records with empty 'amount' field!"
    )
    assert ManufacturingCost.objects.filter(amount__isnull=True).count() == 0, (
        "There are still ManufacturingCost records with empty 'amount' field!"
    )


class Migration(migrations.Migration):
    """Run a migration to ensure that all existing ManufacturingCost records have a non-empty 'amount' field, and then alter the field to be non-blank and non-null."""

    dependencies = [
        ("manufacturing_costs", "0006_manufacturingcost_amount_and_more"),
    ]

    operations = [
        migrations.RunPython(fix_empty_amounts, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="manufacturingcost",
            name="amount",
            field=models.CharField(
                help_text="Raw dimensioned quantity for this manufacturing cost",
                max_length=25,
                verbose_name="Amount",
            ),
        ),
    ]
